services:

  web-api:
    build:
        context: ./App
        dockerfile: ./Dockerfile
    volumes:
      - ./App:/app
    ports:
      - 8000:8000
    command: uvicorn src.main:app --reload --host=0.0.0.0 --port=8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:device_data_db_passwd@db:5432/device_data_db

  db:
    image: postgres 
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=device_data_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=device_data_db_passwd
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  web-api:
  db-data:

